export const en = {
  atleta: {
    base: [
      "Success is never accidental. It is hard work, perseverance, learning, study, sacrifice and, above all, love for what you do. – Pelé",
      "Don't measure yourself by what you have accomplished, but by what you should have accomplished with your ability. – John Wooden",
      "Excellence is not an isolated act, but a habit. You are what you repeatedly do. – Aristotle",
      "Talent wins the first game. Teamwork and intelligence win the championship. – Michael Jordan",
      "If you don't challenge yourself, you don't change. – Fred DeVito",
      "The way to get started is to stop talking and start doing. – Walt Disney",
      "Don't stop when you're tired. Stop when you're done. – David Goggins",
      "Champions keep playing until they get it right. – Billie Jean King",
      "Failure is the opportunity to begin again, this time more intelligently. – Henry Ford",
      "Motivation gets you started. Habit keeps you going. – Jim Ryun",
      "Every day is a new opportunity to improve.",
      "Today's sacrifice is tomorrow's success.",
      "Those willing to sweat more than others, in the end reap more.",
      "Don't wish it were easier, wish you were better. – Jim Rohn",
      "The price of excellence is constant discipline.",
      "Win first in your mind, then on the field.",
      "Focus is the bridge between goals and reality.",
      "Do today what others don't, so tomorrow you can do what others can't.",
      "The true professional trains hard even when no one is watching.",
      "It's not the days that pass that matter, it's what you do to make them count.",
    ],
    strong: [
      "While you study trajectories and movements to anticipate the play, someone else is running faster than you to beat you to it.",
      "The field never lies: you can make up any excuse in the locker room, but your ninety minutes speak exactly for you.",
      "Being on the bench or on a B team is not a sentence: it's the exact measure of how much you still have to prove to those who didn't believe in you.",
      "The ball arrives where it needs to only if you have the mental clarity to read it before others. If you're late, it's never the teammate's fault who passed it.",
      "The difference between those who watch the game and those who decide it lies in that extra second of composure under pressure.",
      "You don't need applause. You need a clean interception, a desperate recovery and the awareness of having shut the door.",
      "Talent without a lucid reading of the game is just running in vain.",
      "If you want the starting jersey in the A team, you must earn it so much that keeping you out becomes impossible for the coach.",
      "Cramps pass, fatigue is forgotten, but the regret of not having given everything in that challenge stays with you forever.",
      "Looking opponents in the eyes before the whistle and knowing you worked twice as hard as them in summer: that's true confidence.",
      "Physical fatigue is just a lie your brain invents because it's afraid of truly pushing hard.",
      "You don't learn to kick under pressure in front of a crowd: you learn it when you're alone at the end of practice repeating the same technical gesture for the hundredth time.",
      "Your role isn't what's written on the tactical board, it's the space you manage to conquer with your intelligence.",
      "A mediocre player looks for someone to blame. An athlete looks for solutions in their own performance.",
      "If you want to play at a higher level, you must start thinking at a higher level, even before touching the ball.",
      "No one will give you a millimeter of field. You must take it with your running, your head and your technique.",
      "Fatigue is temporary, the reserve label stays with you until you prove who you are.",
      "The sweat shed on days you didn't feel like taking the field is the only sweat that will save you when the game gets tough.",
      "You can't expect the team to change pace if you're the first to slow down when the rhythm picks up.",
      "The field is the only incorruptible judge. And today, what did it say about you?",
    ],
    brutal: [
      "You're wasting your potential every single time you decide to settle because 'it's too hot today' or 'there's plenty of time'. Time owes you nothing.",
      "While you're resting, out there someone has the exact same dream as you, but is sweating twice as hard to snatch it from your hands.",
      "Your excuses are perfect. Too bad excuses never won anything and never got anyone anywhere in any championship.",
      "You are exactly where you deserve to be based on what you invested yesterday. If you don't like your current situation, stop complaining and start working hard for real.",
      "Mediocrity feeds on 'I'll start tomorrow'. Have you actually started or are you just collecting perfect plans you never execute?",
      "No one will come to save you, no one will take you by the hand to bring you to the A team if you don't prove to be a genius in your head before your feet.",
      "Your potential talent isn't worth a penny if it stays locked in your head. What you don't bring out on the field doesn't exist.",
      "Want to level up? Stop planning appearances and start building substance, getting your hands dirty.",
      "You are your own first saboteur when you blame bad luck, the coach or others for a goal you're not reaching.",
      "The truth sucks: if you're not the best today, it's because you didn't do what it took to be.",
      "Your rivals have no mercy on you. Why the hell should you have mercy on yourself when you train?",
      "A perfect routine, a perfect plan are worth nothing if you're the one who quits at the best moment.",
      "Stop acting like you have all the time in the world. Your age is the moment you build who you'll be forever; the rest is just distractions.",
      "If you keep doing what you've always done, you'll get exactly what you've always gotten: zero.",
      "It hurts to hear, but if you're not a starter today, there's a reason. Go find it in the mirror and fix it.",
      "Failure isn't falling; failure is deciding to stay down and invent a logical justification.",
      "You don't lack luck, you lack fierce hunger, the kind that makes you close your eyes and push when your body begs to stop.",
      "Everyone wants to win the cup, but very few are willing to throw up from exhaustion to earn it on a Tuesday afternoon behind closed doors.",
      "It's you who decides whether you're a protagonist or a mere spectator of your own life. Choose now.",
      "Enough talk. Turn off the screen, close the tabs, get up from that chair and go do what you need to do.",
    ],
  },
  studente: {
    base: [
      "Success in studying isn't a stroke of luck, but the result of constant planning and a solid method.",
      "Don't aim to be perfect, aim to be consistent. Every day a small step forward.",
      "The mind is not a vessel to be filled, but a fire to be kindled. – Plutarch",
      "The best way to predict your academic future is to create it today with open books.",
      "Talent gives you the spark, but daily practice is what gets you to a solid passing grade and then excellence.",
      "Those who study with a method don't work twice as hard the night before the test.",
      "Every formula understood, every theorem proven and every page studied is a brick for your tomorrow.",
      "Focus is the filter that separates those who study to pass the test from those who study to truly understand.",
      "Don't put off until tomorrow what you can understand today: academic debts pile up exactly like distractions.",
      "Discipline beats talent every single day talent decides not to open the book.",
      "The test grade is just the thermometer of how hard you worked in the days before.",
      "One hour of intense, targeted study is worth more than four hours with the book open and your mind elsewhere.",
      "Curiosity is the engine of the science student: don't memorize things, always ask yourself why.",
      "Don't wish the test were easier, wish you had studied more deeply.",
      "True studying is what you do when no one is checking on you and the temptation to close everything is at its highest.",
      "Getting an exercise wrong at home serves to not get it wrong on the test the next day.",
      "The clarity of a concept in your mind shows in how simply you can explain it.",
      "Time invested in books is never wasted time, it's the only capital no one can ever take from you.",
      "Organizing your study day means earning the freedom to enjoy the rest of the afternoon.",
      "Do today what other students put off until tonight, so tomorrow you'll be one step ahead.",
    ],
    strong: [
      "While you complain about the difficulty of the math curriculum, a classmate is already solving that damn integral you can't get into your head.",
      "The electronic gradebook doesn't lie: you can't blame the teacher if your average exactly reflects the superficial studying you did.",
      "A seven or eight average isn't built the night before the semester ends: it's defended day after day with scheduled oral exams and constant practice.",
      "A failing grade isn't the end of the world, but it's a slap in the face that should wake you up before it becomes a debt in June.",
      "The difference between those who leave high school with top marks and those who struggle lies in that extra half hour spent redoing exercises until the mechanism gets into your fingers.",
      "You don't need a lucky stroke of genius to pass; you need the clarity to read the prompt and apply the method you practiced at home.",
      "Mental fatigue after three hours of physics or Latin is real, but that's exactly where true student resilience is formed.",
      "If you want to aim for high grades, you must stop studying to barely pass and start studying to dominate the subject.",
      "Teachers immediately see who understood the concept and who just memorized the little rule without knowing what it means.",
      "Staring at the blank test page and cursing the moment you skipped the review exercises: that's the hardest lesson high school teaches you.",
      "The fear of the test disappears the exact moment you know you've redone those exercises three times in a row at home.",
      "You can't expect to understand physics if you approach studying with the same attention you use to scroll social media on your phone.",
      "Your grade doesn't define your worth as a person, but it defines to the millimeter the effectiveness of your study method and your dedication.",
      "A mediocre student makes excuses about books being too hard or teachers too strict. A strong student opens the textbook and learns the proof.",
      "If you want to raise your overall average, you must start treating every single subject as if it were the most important one on your report card.",
      "No one will give you an extra point out of pity. In science high school numbers speak clearly and formulas don't forgive distractions.",
      "Anxiety before an oral exam is just the consequence of not feeling 100% ready. Fix it by preparing so much that fear has no room.",
      "Sweating over books in the heaviest weeks is the only price to pay to not find yourself drowning at the end of the year.",
      "You can't expect your mind to be sharp if you feed it constant distractions while trying to study.",
      "The gradebook is open, the average is calculated. And today, what did you do to improve it?",
    ],
    brutal: [
      "You're flushing your potential down the toilet every time you say 'I'll just scrape a six anyway', settling for mediocrity.",
      "While you procrastinate with your phone in hand, someone else in your same class is studying that chapter to steal the top of the class podium from you.",
      "Your excuses about 'the teacher has it out for me' are pathetic. If you get a five, nine times out of ten it's because you didn't study well enough.",
      "You are exactly where your laziness took you. If your report card sucks, stop blaming the school system and look in the mirror.",
      "Your fake technique of 'I study at the last minute' only works for trivial things. In advanced high school it will destroy you without mercy.",
      "No one will come to save your average at the end of the year. If you don't get to work now, you'll sweat off all your debts alone in July.",
      "Your intellect isn't worth a penny if it's blocked by mental laziness. What you don't understand and don't deepen remains a black hole in your head.",
      "Want to be the big shot, want to manage your own things? Start by proving you can handle a string of advanced subjects without crying about it.",
      "You are your own first saboteur when you shut down your brain in front of a slightly longer math problem and say 'I don't know how to do this'.",
      "The hard truth is that if you get low grades today, it's not because school is unfair, but because your effort is pathetic compared to what you could do.",
      "Your teachers have no interest in making you fail, but they also have no intention of gifting you a promotion if you don't lift a finger.",
      "A brilliant software idea is worth nothing if you then miserably fail on the academic basics because you can't be bothered to focus.",
      "Stop acting like school is a waste of time. The way you approach studying now is exactly the way you'll approach any job as an adult.",
      "If you keep studying with passing as your only goal, you'll get a mediocre life. Wake up.",
      "It hurts to admit, but if you don't understand a topic it's not because you're hopeless, it's because you gave up too soon at the first difficulty.",
      "Failure on a test isn't bad luck; failure is deciding not to analyze the mistakes you made so you never repeat them.",
      "You don't lack the intelligence to excel in science high school: you lack the iron discipline to sit down and study even when the last thing you want to do is open the book.",
      "Everyone wants a nine average and applause at graduation, but very few are willing to turn off their phone and sweat blood over books in the afternoon.",
      "It's you who chooses whether to be a mediocre student who survives oral exams or a person capable of dominating any subject in front of them.",
      "Enough excuses. Turn off notifications, open the book to the right page and start studying now.",
    ],
  },
  professionista: {
    base: [
      "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill",
      "Don't find customers for your products, find products for your customers. – Seth Godin",
      "Quality means doing things well when no one is watching. – Henry Ford",
      "The best way to predict the future is to invent it. – Alan Kay",
      "The biggest risk is not taking any risk. In a world that's changing fast, the only strategy guaranteed to fail is not taking risks. – Mark Zuckerberg",
      "The price of success is hard work, dedication and the determination that, win or lose, we applied the best of ourselves to the task. – Vince Lombardi",
      "Don't focus on having a big company; focus on solving a huge problem excellently.",
      "Discipline is the bridge between goals and business results. – Jim Rohn",
      "A successful business is built on decisions made with clarity when everything around is chaos.",
      "Execution beats the brilliant idea every single day of the week.",
      "Make your customers so satisfied they never have to look elsewhere.",
      "Profit is the market's opinion of the value you're creating.",
      "Those who don't innovate and don't adapt end up becoming irrelevant.",
      "Don't plan for the quarter: plan to build an ecosystem that lasts over time.",
      "The true professional doesn't wait for the perfect moment; they take control and create it.",
      "A company's value is directly proportional to the real problems it can solve.",
      "Clarity of vision determines the speed of results.",
      "Time is an entrepreneur's scarcest resource: protect it and invest it only where there's a return.",
      "Commercial success is the inevitable consequence of an excellent product and an iron ethic.",
      "Work on your project with the same intensity you demand the market to pay you back.",
    ],
    strong: [
      "While you analyze details for the hundredth time, someone else on the market launched an imperfect but working product and is stealing your customers.",
      "The market has no mercy for unexecuted ideas: they're worth zero until they generate real value.",
      "A project's economic sustainability isn't calculated on optimistic Excel spreadsheets, but on how many users actually pay at the end of the month.",
      "A market failure isn't bad luck, it's brutal feedback telling you your offer doesn't respond to a real need.",
      "The difference between those who suffer the market and those who lead it lies in speed of adaptation and the courage to cut dead branches.",
      "You don't need a perfect partner or infinite capital to start: you need ruthless execution and the ability to sell value.",
      "Mental fatigue after a day spent solving business and technical problems is the price of independence.",
      "If you want to build a solid business, you must stop looking for excuses in bureaucracy or economic conditions and focus on what you can control.",
      "Customers don't buy your software because it's beautiful: they buy it because it solves a nuisance that costs them time or money.",
      "Looking at conversion metrics and seeing zero: this is the naked, raw reality that forces you to correct course.",
      "Financial pressure and the search for first revenues aren't an obstacle, they're the filter that separates those who do business out of passion from those who try as a hobby.",
      "You can't expect your project to scale if you're the first bottleneck who can't delegate or automate.",
      "Your brand is worth exactly as much as the trust the last unsatisfied user places in your support.",
      "A mediocre entrepreneur seeks subsidies and external excuses. A real businessman seeks distribution channels and optimizes costs.",
      "If you want to invoice significant figures, you must stop thinking small and start structuring every process as if the company had ten thousand users.",
      "No one will gift you visibility or conversions. Market shares are conquered with the right offer at the right time.",
      "Launch and customer acquisition anxiety disappears only when the product is so useful it almost sells itself through word of mouth.",
      "The sweat shed on budgets, code or commercial strategies late at night is the only capital no one can ever take from you.",
      "You can't expect your business to grow if you treat your activity with the same superficiality as a summer hobby.",
      "The company bank account is the only incorruptible judge of your effectiveness. And today, what does it say about you?",
    ],
    brutal: [
      "You're flushing your time and skills down the toilet every time you make up the excuse that 'the market is saturated' or 'there's no funding'.",
      "While you procrastinate over useless aesthetic details, out there a hungry competitor is closing deals and taking your potential customers.",
      "Your justifications that no one uses your app because 'people don't get quality' are pathetic. If it doesn't convert, the error is in your positioning or your offer.",
      "You are exactly where your level of execution took you. If the project stagnates, stop blaming algorithms and look in the mirror.",
      "Your fake strategy of 'I'll wait until everything is perfect before launching' is only guaranteeing you'll arrive late to market.",
      "No one will come to save your company or bring customers to your door. If you don't roll up your sleeves to do outreach and sell, you fail.",
      "Your perfect code or brilliant ideas aren't worth a penny if no one is willing to pay for them. An idea without a market isn't a business, it's a secret diary.",
      "Want to get serious, want to invoice, want your financial independence? Start by proving you can generate the first real euro, without crying about it.",
      "You are your own first saboteur when you give up on sales the moment things get difficult and contacts don't respond.",
      "The hard truth is that if your business doesn't invoice, it's not because the world has it out for you, but because your value proposition is pathetic or no one can communicate it.",
      "Your users have no interest in doing you a favor: they'll use your platform only if it solves a real problem of theirs better than anyone else.",
      "A brilliant idea on paper is worth nothing if you miserably fail on practical management, deadlines or customer relations because you can't be bothered to hustle.",
      "Stop acting like you have a millionaire investment fund behind you covering your mistakes. Money is made in the field, optimizing every single resource.",
      "If you keep managing your project with the 'I'll do it when I feel like it' mentality, you'll get a guaranteed failure. Wake up.",
      "It hurts to admit, but if a user tries your app and closes it after two seconds, it's not their fault: it's your fault for not creating addiction or immediate utility.",
      "A launch failure isn't bad luck; failure is deciding not to analyze the log data to understand where you went wrong.",
      "You don't lack the talent to do business: you lack the iron discipline to get up and push the cart even when the market's response is cold.",
      "Everyone wants financial freedom and the spotlight of success, but very few are willing to take on the risk, the no's and the invisible work behind the scenes.",
      "It's you who chooses whether to be a paper project manager who collects slides or an entrepreneur who turns problems into revenue.",
      "Enough excuses. Close the theoretical simulations, go talk to the real market and start building concrete results now.",
    ],
  },
  base: {
    base: [
      "Success is never accidental; it is the result of hard work, perseverance and constant sacrifice.",
      "Excellence is not an isolated act, but a habit rooted in what you do every day. – Aristotle",
      "Motivation gets you started, but iron discipline is what carries you all the way to the end.",
      "Don't stop when you're tired, stop when the work is done. – David Goggins",
      "The best way to predict the future is to build it brick by brick with your actions today.",
      "Those willing to sweat more than others will, in the end, always reap the best rewards.",
      "The price of excellence is consistency on the days when you'd gladly skip the struggle.",
      "Win first in your mind, then the outside reality will adjust accordingly.",
      "The true professional completes the task even when no one is watching.",
      "It's not the passing days that matter, but only the intensity and direction you give to each of them.",
    ],
    strong: [
      "While you dissect excuses to postpone, someone else with the same ambition is grinding to take your place.",
      "Reality gives no discounts: your current level exactly reflects the real investment you made yesterday, not your intentions.",
      "The difference between those who suffer events and those who steer them lies in the composure with which they read the context under pressure.",
      "A mediocre result is not a final sentence, but it is the exact mirror of a superficial commitment.",
      "Mental and physical fatigue is only a fictitious boundary the mind erects to protect itself from true growth.",
      "If you want to aim for the top, you must stop settling for adequacy and start demanding excellence of yourself.",
      "No one will hand you a millimeter of space: you earn your position with sweat and seize it with your mind and your actions.",
      "The judgment of the field, the market, or the numbers is incorruptible: it speaks plainly and wipes out every justification.",
      "Anxiety and fear disappear the exact moment you prepare so thoroughly that failure becomes almost impossible.",
      "The sweat shed in dark days is the only capital that will save you when the test turns ruthless.",
    ],
    brutal: [
      "You're throwing away your potential every single time you choose the comfortable path of excuses over the hard path of execution.",
      "Your justifications are perfect, but with justifications no one has ever built a damn thing.",
      "You are exactly where your laziness took you. Stop blaming the system or bad luck and look in the mirror.",
      "Your potential talent isn't worth a single penny as long as it stays locked in your head without turning into concrete facts.",
      "Mediocrity feeds on 'I'll start tomorrow'. Have you actually started or are you just collecting perfect theoretical plans?",
      "No one will come to save you, no one will take you by the hand. If you don't roll up your sleeves first, you'll stand by and watch others win.",
      "The hard truth is that if you don't get what you want today, it's because your real effort is pathetic compared to your grand proclamations.",
      "Everyone wants the finish line and the applause, but very few are willing to throw up from exhaustion in the silence of weekdays.",
      "If you keep doing what you've always done, you'll get exactly the nothing you have in your hands right now. Wake up.",
      "Enough talk, enough mental simulations: turn off distractions, face the problem and go do what you must.",
    ],
  },
};