export const es = {
  atleta: {
    base: [
      "El éxito nunca es accidental. Es trabajo duro, perseverancia, aprendizaje, estudio, sacrificio y, sobre todo, amor por lo que haces. – Pelé",
      "No te midas por lo que has alcanzado, sino por lo que deberías haber alcanzado con tu habilidad. – John Wooden",
      "La excelencia no es un acto aislado, sino un hábito. Tú eres lo que haces repetidamente. – Aristóteles",
      "El talento te hace ganar el primer partido. El trabajo en equipo y la inteligencia te hacen ganar el campeonato. – Michael Jordan",
      "Si no te desafías, no cambias. – Fred DeVito",
      "La forma de empezar es dejar de hablar y empezar a hacer. – Walt Disney",
      "No te detengas cuando estés cansado. Detente cuando hayas terminado. – David Goggins",
      "Los campeones siguen jugando hasta que hacen las cosas bien. – Billie Jean King",
      "El fracaso es la oportunidad de empezar de nuevo, esta vez de forma más inteligente. – Henry Ford",
      "La motivación te hace empezar. El hábito te mantiene en marcha. – Jim Ryun",
      "Cada día es una nueva oportunidad para mejorar.",
      "El sacrificio de hoy es el éxito de mañana.",
      "Quien está dispuesto a sudar más que los demás, al final recoge más.",
      "No desees que fuera más fácil, desea ser mejor tú. – Jim Rohn",
      "El precio de la excelencia es la disciplina constante.",
      "Gana primero en tu mente, luego en el campo.",
      "La concentración es el puente entre los objetivos y la realidad.",
      "Haz hoy lo que otros no hacen, para que mañana puedas hacer lo que otros no pueden.",
      "El verdadero profesional entrena duro incluso cuando nadie lo está mirando.",
      "No cuentan los días que pasan, cuenta lo que haces para que cuenten.",
    ],
    strong: [
      "Mientras tú estudias las trayectorias y los movimientos para anticipar la jugada, otro está corriendo más fuerte que tú para ganarte.",
      "El campo nunca miente: puedes inventarte cualquier excusa en el vestuario, pero tus noventa minutos hablan exactamente por ti.",
      "Estar en el banquillo o en un equipo B no es una condena: es la medida exacta de cuánto aún tienes que demostrar a quienes no creyeron en ti.",
      "El balón llega donde tiene que llegar solo si tienes la lucidez mental para leerlo antes que los demás. Si llegas tarde, la culpa nunca es del compañero que te lo pasó.",
      "La diferencia entre quien mira el partido y quien lo decide está en ese segundo extra de frialdad bajo presión.",
      "No necesitas un aplauso. Necesitas una intercepción limpia, una recuperación desesperada y la conciencia de haber cerrado la puerta.",
      "El talento sin una lectura lúcida del juego es solo carrera en vano.",
      "Si quieres la camiseta de titular en el equipo A, tienes que merecerla tanto que mantenerte fuera sea imposible para el entrenador.",
      "Los calambres pasan, el cansancio se olvida, pero el arrepentimiento de no haberlo dado todo en ese duelo se queda contigo para siempre.",
      "Mirar a los rivales a los ojos antes del silbato inicial y saber que trabajaste el doble que ellos en verano: esa es la verdadera seguridad.",
      "El cansancio físico es solo una mentira que tu cerebro inventa porque tiene miedo de esforzarse de verdad.",
      "No aprendes a patear bajo presión cuando hay público: lo aprendes cuando estás solo al final del entrenamiento repitiendo el mismo gesto técnico por centésima vez.",
      "Tu rol no es lo que está escrito en la pizarra táctica, es el espacio que logras conquistar con tu inteligencia.",
      "Un jugador mediocre busca culpables. Un atleta busca soluciones en su propio rendimiento.",
      "Si quieres jugar a un nivel superior, debes empezar a pensar a un nivel superior, antes incluso de tocar el balón.",
      "Nadie te regalará un milímetro de campo. Tienes que ganártelo con la carrera, con la cabeza y con la técnica.",
      "El cansancio es temporal, la etiqueta de suplente te la llevas hasta que demuestras quién eres.",
      "El sudor derramado en los días que no tenías ganas de salir al campo es el único que te salvará cuando el partido se pone duro.",
      "No puedes pretender que el equipo cambie el ritmo si eres el primero en frenar cuando la intensidad sube.",
      "El campo es el único juez incorruptible. ¿Y hoy, qué dijo de ti?",
    ],
    brutal: [
      "Estás desperdiciando tu potencial cada vez que decides conformarte porque 'hoy hace demasiado calor' o 'total hay tiempo'. El tiempo no te debe nada.",
      "Mientras tú descansas, ahí fuera hay alguien que tiene exactamente tu mismo sueño, pero está sudando el doble para arrancártelo de las manos.",
      "Tus excusas son perfectas. Lástima que con las excusas no se gana absolutamente nada ni se abre camino en ningún campeonato.",
      "Estás exactamente donde te mereces estar según lo que invertiste ayer. Si no te gusta tu situación actual, deja de quejarte y empieza a trabajar en serio.",
      "La mediocridad se alimenta del 'mañana empiezo'. ¿Has empezado de verdad o solo estás coleccionando planes perfectos que no ejecutas?",
      "Nadie vendrá a salvarte, nadie te tomará de la mano para llevarte al equipo A si no demuestras ser un fenómeno de cabeza antes que de pies.",
      "Tu talento potencial no vale un céntimo si se queda encerrado en tu cabeza. Lo que no sacas al campo no existe.",
      "¿Quieres dar un salto de calidad? Deja de planificar apariencias y empieza a construir sustancia, manchándote las manos.",
      "Eres tu primer saboteador cuando echas la culpa a la mala suerte, al entrenador o a los demás por un objetivo que no estás alcanzando.",
      "La verdad duele: si hoy no eres el mejor, es porque no hiciste lo necesario para serlo.",
      "Tus rivales no tienen piedad de ti. ¿Por qué diablos deberías tenerla tú de ti mismo cuando entrenas?",
      "Una rutina perfecta, un plan perfecto no sirven de nada si luego eres tú el que abandona en el mejor momento.",
      "Deja de actuar como si tuvieras todo el tiempo del mundo. Tu edad es el momento en que construyes quién serás para siempre; el resto son solo distracciones.",
      "Si sigues haciendo lo que siempre has hecho, obtendrás exactamente lo que siempre has obtenido: cero.",
      "Duele escucharlo, pero si hoy no eres titular, hay un motivo. Búscalo en el espejo y arréglalo.",
      "El fracaso no es caer; el fracaso es decidir quedarse tumbado inventándose una justificación lógica.",
      "No te falta suerte, te falta hambre feroz, la que te hace cerrar los ojos y empujar cuando el cuerpo ruega que pares.",
      "Todos quieren ganar la copa, pero muy pocos están dispuestos a vomitar de cansancio para ganársela un martes por la tarde a puerta cerrada.",
      "Eres tú quien decide si eres protagonista o simple espectador de tu propia vida. Elige ahora.",
      "Suficiente charla. Apaga la pantalla, cierra las pestañas, levántate de esa silla y ve a hacer lo que tienes que hacer.",
    ],
  },
  studente: {
    base: [
      "El éxito en el estudio no es un golpe de suerte, sino el resultado de una planificación constante y un método sólido.",
      "No apuntes a ser perfecto, apunta a ser constante. Cada día un pequeño paso adelante.",
      "La mente no es un vaso por llenar, sino un fuego por encender. – Plutarco",
      "La mejor manera de predecir tu futuro escolar es crearlo hoy con los libros abiertos.",
      "El talento te da la chispa, pero es la práctica diaria la que te lleva al aprobado y luego a la excelencia.",
      "Quien estudia con método no trabaja el doble la noche antes del examen.",
      "Cada fórmula comprendida, cada teorema demostrado y cada página estudiada son un ladrillo para tu mañana.",
      "La concentración es el filtro que separa a quien estudia para aprobar de quien estudia para entender de verdad.",
      "No dejes para mañana lo que puedes entender hoy: los deberes pendientes se acumulan exactamente como las distracciones.",
      "La disciplina vence al talento cada día que el talento decide no abrir el libro.",
      "La nota del examen es solo el termómetro de lo duro que trabajaste en los días anteriores.",
      "Una hora de estudio intenso y dirigido vale más que cuatro horas con el libro abierto y la mente en otro lugar.",
      "La curiosidad es el motor del estudiante de ciencias: no memorices, pregúntate siempre el porqué.",
      "No desees que el examen sea más fácil, desea haber estudiado con más profundidad.",
      "El verdadero estudio es el que haces cuando nadie te controla y la tentación de cerrar todo es enorme.",
      "Equivocarse en un ejercicio en casa sirve para no equivocarse en el examen del día siguiente.",
      "La claridad de un concepto en tu mente se ve en lo sencillo que es explicarlo.",
      "El tiempo invertido en los libros nunca es tiempo perdido, es el único capital que nadie podrá quitarte.",
      "Organizar tu jornada de estudio significa ganar la libertad de disfrutar el resto de la tarde.",
      "Haz hoy lo que otros estudiantes dejan para esta noche, así mañana estarás un paso adelante.",
    ],
    strong: [
      "Mientras te quejas de la dificultad del temario de matemáticas, un compañero tuyo ya está resolviendo esa maldita integral que no te entra en la cabeza.",
      "El boletín electrónico no miente: no puedes culpar al profesor si tu media refleja exactamente el estudio superficial que has hecho.",
      "La media del siete o del ocho no se construye la noche antes del trimestre: se defiende día a día con interrogaciones programadas y ejercicio constante.",
      "Un suspenso no es el fin del mundo, pero es una bofetada que debe despertarte antes de que se convierta en una deuda en junio.",
      "La diferencia entre quien sale del instituto con la nota máxima y quien va arrastrando está en esa media hora extra repitiendo ejercicios hasta que el mecanismo te entra en los dedos.",
      "No necesitas un golpe de genio para aprobar; necesitas la lucidez de leer el enunciado y aplicar el método que has repetido en casa.",
      "El cansancio mental después de tres horas de física o latín es real, pero es justo ahí donde se forma la verdadera resistencia del estudiante.",
      "Si quieres apuntar a notas altas, debes dejar de estudiar para aprobar y empezar a estudiar para dominar la materia.",
      "Los profesores ven enseguida quién entendió el concepto y quién solo memorizó la reglita sin saber qué significa.",
      "Mirar la página en blanco del examen y maldecir el momento en que saltaste los ejercicios de repaso: esa es la lección más dura que el instituto te enseña.",
      "El miedo al examen desaparece en el momento exacto en que sabes que has rehecho esos ejercicios tres veces seguidas en casa.",
      "No puedes pretender entender la física si afrontas el estudio con la misma atención que usas para navegar las redes en el móvil.",
      "Tu nota no define tu valor como persona, pero define al milímetro la eficacia de tu método de estudio y tu dedicación.",
      "Un estudiante mediocre busca excusas en libros demasiado difíciles o profesores demasiado exigentes. Un estudiante fuerte abre el libro y aprende la demostración.",
      "Si quieres subir tu media general, debes empezar a tratar cada asignatura como si fuera la más importante de tu boletín.",
      "Nadie te regalará un punto extra por compasión. En el bachillerato científico los números hablan claro y las fórmulas no perdonan las distracciones.",
      "La ansiedad antes de una interrogación es solo la consecuencia de no sentirte al 100%. Arréglalo preparándote tanto que el miedo no tenga espacio.",
      "El sudor sobre los libros en las semanas más pesadas es el único precio a pagar para no encontrarte con el agua al cuello a final de año.",
      "No puedes pretender que tu mente sea brillante si la alimentas con distracciones constantes mientras intentas estudiar.",
      "El boletín está abierto, la media está calculada. ¿Y hoy, qué has hecho para mejorarla?",
    ],
    brutal: [
      "Estás tirando tu potencial por el inodoro cada vez que dices 'total me apaño con un seis', conformándote con la mediocridad.",
      "Mientras procrastinas con el móvil en la mano, hay alguien más en tu misma clase estudiando ese capítulo para robarte el podio de la media más alta.",
      "Tus justificaciones de 'el profe me tiene manía' son patéticas. Si sacas un cinco, nueve de cada diez veces es porque no has estudiado lo suficiente.",
      "Estás exactamente donde tu pereza te ha llevado. Si tu boletín da asco, deja de culpar al sistema educativo y mírate al espejo.",
      "Tu falsa técnica del 'total yo estudio a última hora' solo funciona con cosas triviales. En el bachillerato avanzado te destruirá sin piedad.",
      "Nadie vendrá a salvarte la media a final de año. Si no te pones a estudiar ahora, los deberes te los sudas tú solo en julio.",
      "Tu intelecto no vale un céntimo si está bloqueado por la pereza mental. Lo que no entiendes y no profundizas queda como un agujero negro en tu cabeza.",
      "¿Quieres ser el grande, quieres gestionar tus cosas? Empieza demostrando que sabes gestionar una ristra de asignaturas avanzadas sin lloriquear.",
      "Eres tu primer saboteador cuando apagas el cerebro ante un problema de matemáticas un poco más largo de lo normal y dices 'esto no sé hacerlo'.",
      "La dura verdad es que si hoy sacas notas bajas, no es porque la escuela sea injusta, sino porque tu esfuerzo da pena comparado con lo que podrías hacer.",
      "Tus profesores no tienen interés en hacerte suspender, pero tampoco tienen intención de regalarte la promoción si no mueves un dedo.",
      "Una idea genial para un software no vale nada si luego suspendes miserablemente en lo básico porque no tienes ganas de concentrarte.",
      "Deja de actuar como si la escuela fuera una pérdida de tiempo. La forma en que afrontas el estudio ahora es exactamente la forma en que afrontarás cualquier trabajo de adulto.",
      "Si sigues estudiando con el aprobado como única meta, obtendrás una vida mediocre. Despierta.",
      "Duele admitirlo, pero si no entiendes un tema no es porque seas negado, es porque soltaste la presa demasiado pronto a la primera dificultad.",
      "El fracaso en un examen no es mala suerte; el fracaso es decidir no analizar los errores cometidos para no repetirlos jamás.",
      "No te falta inteligencia para destacar en el bachillerato científico: te falta la disciplina férrea de sentarte a estudiar incluso cuando lo último que quieres hacer es abrir el libro.",
      "Todos quieren la media de nueve y los aplausos en la entrega de diplomas, pero muy pocos están dispuestos a apagar el móvil y sangrar sobre los libros por la tarde.",
      "Eres tú quien elige si ser un estudiante mediocre que sobrevive a las interrogaciones o una persona capaz de dominar cualquier materia que tenga delante.",
      "Suficiente excusas. Apaga las notificaciones, abre el libro por la página correcta y empieza a estudiar ahora.",
    ],
  },
  professionista: {
    base: [
      "El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el coraje para continuar. – Winston Churchill",
      "No encuentres clientes para tus productos, encuentra productos para tus clientes. – Seth Godin",
      "Calidad significa hacer las cosas bien cuando nadie está mirando. – Henry Ford",
      "La mejor manera de predecir el futuro es inventarlo. – Alan Kay",
      "El mayor riesgo es no asumir ninguno. En un mundo que cambia rápido, la única estrategia garantizada para fracasar es no arriesgar. – Mark Zuckerberg",
      "El precio del éxito es el trabajo duro, la dedicación y la determinación de haber dado lo mejor de nosotros a la tarea, ganemos o perdamos. – Vince Lombardi",
      "No te concentres en tener una gran empresa; concéntrate en resolver un problema enorme de forma excelente.",
      "La disciplina es el puente entre los objetivos y los resultados empresariales. – Jim Rohn",
      "Un negocio de éxito se basa en decisiones tomadas con lucidez cuando todo alrededor es caos.",
      "La ejecución vence a la idea brillante cada día de la semana.",
      "Haz que tus clientes estén tan satisfechos que nunca tengan que mirar a otro lado.",
      "El beneficio es la opinión del mercado sobre el valor que estás creando.",
      "Quien no innova y no se adapta acaba siendo irrelevante.",
      "No planifiques para el trimestre: planifica para construir un ecosistema que dure en el tiempo.",
      "El verdadero profesional no espera el momento perfecto; toma el control y lo crea.",
      "El valor de una empresa es directamente proporcional a los problemas reales que resuelve.",
      "La claridad de visión determina la velocidad de los resultados.",
      "El tiempo es el recurso más escaso de un emprendedor: protégelo e inviértelo solo donde haya retorno.",
      "El éxito comercial es la consecuencia inevitable de un producto excelente y una ética férrea.",
      "Trabaja en tu proyecto con la misma intensidad con la que exiges que el mercado te pague.",
    ],
    strong: [
      "Mientras analizas los detalles por centésima vez, alguien en el mercado ha lanzado un producto imperfecto pero operativo y te está robando clientes.",
      "El mercado no tiene piedad para las ideas no ejecutadas: valen cero hasta que generan valor real.",
      "La sostenibilidad económica de un proyecto no se calcula en hojas de Excel optimistas, sino en cuántos usuarios pagan de verdad a fin de mes.",
      "Un fracaso de mercado no es mala suerte, es un feedback brutal que te dice que tu oferta no responde a una necesidad real.",
      "La diferencia entre quien sufre el mercado y quien lo dirige está en la velocidad de adaptación y el coraje de cortar las ramas secas.",
      "No necesitas un socio perfecto o un capital infinito para empezar: necesitas ejecución despiadada y la capacidad de vender valor.",
      "El cansancio mental después de un día resolviendo problemas empresariales y técnicos es el precio de la independencia.",
      "Si quieres construir un negocio sólido, debes dejar de buscar excusas en la burocracia o la coyuntura económica y centrarte en lo que puedes controlar.",
      "Los clientes no compran tu software porque sea bonito: lo compran porque les resuelve una molestia que les cuesta tiempo o dinero.",
      "Mirar las métricas de conversión y ver cero: esta es la realidad cruda que te obliga a corregir el tiro.",
      "La presión financiera y la búsqueda de los primeros ingresos no son un obstáculo, son el filtro que separa a quien hace empresa por pasión de quien lo intenta como hobby.",
      "No puedes pretender que tu proyecto escale si tú eres el primer cuello de botella que no sabe delegar ni automatizar.",
      "Tu marca vale exactamente lo que la confianza que el último usuario insatisfecho deposita en tu soporte.",
      "Un emprendedor mediocre busca subvenciones y excusas externas. Un hombre de negocio de verdad busca canales de distribución y optimiza costes.",
      "Si quieres facturar cifras importantes, debes dejar de pensar en pequeño y empezar a estructurar cada proceso como si la empresa tuviera diez mil usuarios.",
      "Nadie te regalará visibilidad ni conversiones. Las cuotas de mercado se conquistan con la oferta adecuada en el momento adecuado.",
      "La ansiedad del lanzamiento y la captación de clientes desaparece solo cuando el producto es tan útil que se vende casi solo por boca a boca.",
      "El sudor derramado en balances, código o estrategias comerciales a altas horas de la noche es el único capital que nadie podrá quitarte.",
      "No puedes pretender que tu negocio crezca si tratas tu actividad con la misma superficialidad que un pasatiempo de verano.",
      "La cuenta bancaria de la empresa es el único juez incorruptible de tu eficacia. ¿Y hoy, qué dice de ti?",
    ],
    brutal: [
      "Estás tirando por el inodoro tu tiempo y tus capacidades cada vez que te inventas la excusa de que 'el mercado está saturado' o 'faltan fondos'.",
      "Mientras procrastinas en detalles estéticos inútiles, ahí fuera hay un competidor hambriento cerrando acuerdos y llevándose a tus clientes potenciales.",
      "Tus justificaciones de que nadie usa tu app porque 'la gente no entiende la calidad' son patéticas. Si no convierte, el error está en tu posicionamiento o tu oferta.",
      "Estás exactamente donde tu nivel de ejecución te ha llevado. Si el proyecto estanca, deja de culpar a los algoritmos y mírate al espejo.",
      "Tu falsa estrategia de 'espero a que todo sea perfecto antes de salir' solo te garantiza llegar tarde al mercado.",
      "Nadie vendrá a salvar tu empresa ni a llevarte clientes a casa. Si no te remangas para hacer outreach y vender, fracasas.",
      "Tu código perfecto o tus ideas geniales no valen un céntimo si no hay nadie dispuesto a pagar por ellos. La idea sin mercado no es un negocio, es un diario secreto.",
      "¿Quieres ir en serio, quieres facturar, quieres tu independencia económica? Empieza demostrando que sabes generar el primer euro real, sin lloriquear.",
      "Eres tu primer saboteador cuando sueltas la presa comercial en cuanto las cosas se ponen difíciles y los contactos no responden.",
      "La dura verdad es que si tu negocio no factura, no es porque el mundo te tenga manía, sino porque tu propuesta de valor da pena o nadie sabe comunicarla.",
      "Tus usuarios no tienen interés en hacerte un favor: usarán tu plataforma solo si resuelve un problema real suyo mejor que nadie.",
      "Una idea brillante en papel no vale nada si luego suspendes en la gestión práctica, los plazos o la relación con el cliente porque no tienes ganas de esforzarte.",
      "Deja de actuar como si tuvieras detrás un fondo de inversión millonario que cubre tus errores. El dinero se hace en el campo, optimizando cada recurso.",
      "Si sigues gestionando tu proyecto con la mentalidad de 'total lo hago cuando tengo ganas', obtendrás un fracaso garantizado. Despierta.",
      "Duele admitirlo, pero si un usuario prueba tu app y la cierra a los dos segundos, no es culpa suya: es tuya por no crear adicción o utilidad inmediata.",
      "El fracaso de un lanzamiento no es mala suerte; el fracaso es decidir no analizar los datos de los logs para entender dónde fallaste.",
      "No te falta talento para emprender: te falta la disciplina férrea de levantarte y empujar el carro incluso cuando la respuesta del mercado es fría.",
      "Todos quieren la libertad financiera y los focos del éxito, pero muy pocos están dispuestos a cargar con el riesgo, los no y el trabajo invisible entre bastidores.",
      "Eres tú quien elige si ser un project manager de papel que colecciona diapositivas o un emprendedor que transforma problemas en facturación.",
      "Suficiente excusas. Cierra las simulaciones teóricas, ve a hablar con el mercado real y empieza a construir resultados concretos ahora.",
    ],
  },
  base: {
    base: [
      "El éxito nunca es accidental; es el resultado del trabajo duro, la perseverancia y el sacrificio constante.",
      "La excelencia no es un acto aislado, sino un hábito arraigado en lo que haces cada día. – Aristóteles",
      "La motivación te hace empezar, pero es la disciplina férrea la que te lleva hasta el final.",
      "No te detengas cuando estés cansado, detente cuando hayas terminado. – David Goggins",
      "La mejor manera de predecir el futuro es construirlo ladrillo a ladrillo con tus acciones de hoy.",
      "Quien está dispuesto a sudar más que los demás, al final siempre recoge los mejores frutos.",
      "El precio de la excelencia es la constancia en los días en que con gusto evitarías la lucha.",
      "Gana primero en tu mente, luego la realidad exterior se ajustará en consecuencia.",
      "El verdadero profesional cumple la tarea incluso cuando nadie lo está mirando.",
      "No cuentan los días que pasan, solo la intensidad y la dirección que das a cada uno de ellos.",
    ],
    strong: [
      "Mientras analizas excusas para posponerlo, otra persona con tu misma ambición está trabajando duro para ocupar tu lugar.",
      "La realidad no hace descuentos: tu nivel actual refleja exactamente la inversión real que hiciste ayer, no tus intenciones.",
      "La diferencia entre quien sufre los acontecimientos y quien los dirige está en la frialdad con la que se lee el contexto bajo presión.",
      "Un resultado mediocre no es una condena definitiva, sino el espejo exacto de un compromiso superficial.",
      "El cansancio mental y físico es solo un límite ficticio que la mente erige para protegerse del verdadero crecimiento.",
      "Si quieres apuntar a la cima, debes dejar de conformarte con lo suficiente y empezar a exigir excelencia a ti mismo.",
      "Nadie te regalará un milímetro de espacio: te ganas tu posici\u00f3n sudando y la conquistas con la mente y con los hechos.",
      "El juicio del campo, del mercado o de los n\u00fameros es incorruptible: habla claro y anula toda justificaci\u00f3n.",
      "La ansiedad y el miedo desaparecen en el momento exacto en que te preparas tanto que el fracaso se vuelve casi imposible.",
      "El sudor derramado en los d\u00edas oscuros es el \u00fanico capital que te salvar\u00e1 cuando la prueba sea despiadada.",
    ],
    brutal: [
      "Estás desperdiciando tu potencial cada vez que eliges el cómodo camino de la excusa en lugar del duro camino de la ejecución.",
      "Tus justificaciones son perfectas, pero con justificaciones nunca se ha construido una maldita cosa.",
      "Estás exactamente donde tu pereza te ha llevado. Deja de culpar al sistema o a la mala suerte y mírate al espejo.",
      "Tu talento potencial no vale un solo céntimo mientras se quede encerrado en tu cabeza sin convertirse en hechos concretos.",
      "La mediocridad se alimenta del 'mañana empiezo'. ¿Has empezado de verdad o solo estás coleccionando planes teóricos perfectos?",
      "Nadie vendrá a salvarte, nadie te tomará de la mano. Si no te remangas tú primero, te quedarás mirando a otros ganar.",
      "La dura verdad es que si hoy no obtienes lo que quieres, es porque tu esfuerzo real da pena comparado con tus grandes proclamas.",
      "Todos quieren la meta y los aplausos, pero muy pocos están dispuestos a vomitar de cansancio en el silencio de los días laborables.",
      "Si sigues haciendo lo que siempre has hecho, obtendrás exactamente la nada que tienes en las manos ahora mismo. Despierta.",
      "Suficiente charla, suficiente simulaciones mentales: apaga las distracciones, afronta el problema y ve a hacer lo que debes.",
    ],
  },
};