export const fr = {
  atleta: {
    base: [
      "Le succès n'est jamais accidentel. C'est le travail acharné, la persévérance, l'apprentissage, l'étude, le sacrifice et, surtout, l'amour pour ce que tu fais. – Pelé",
      "Ne te mesure pas à ce que tu as accompli, mais à ce que tu aurais dû accomplir avec tes capacités. – John Wooden",
      "L'excellence n'est pas un acte isolé, mais une habitude. Tu es ce que tu fais à plusieurs reprises. – Aristote",
      "Le talent te fait gagner le premier match. Le travail d'équipe et l'intelligence te font gagner le championnat. – Michael Jordan",
      "Si tu ne te défies pas, tu ne changes pas. – Fred DeVito",
      "La façon de commencer est d'arrêter de parler et de commencer à faire. – Walt Disney",
      "Ne t'arrête pas quand tu es fatigué. Arrête-toi quand tu as fini. – David Goggins",
      "Les champions continuent à jouer jusqu'à ce qu'ils fassent les choses correctement. – Billie Jean King",
      "L'échec est l'opportunité de recommencer, cette fois de manière plus intelligente. – Henry Ford",
      "La motivation te fait démarrer. L'habitude te fait continuer. – Jim Ryun",
      "Chaque jour est une nouvelle opportunité de progresser.",
      "Le sacrifice d'aujourd'hui est le succès de demain.",
      "Celui qui est prêt à transpirer plus que les autres récolte finalement davantage.",
      "Ne souhaite pas que ce soit plus facile, souhaite être meilleur. – Jim Rohn",
      "Le prix de l'excellence est une discipline constante.",
      "Gagne d'abord dans ton esprit, puis sur le terrain.",
      "La concentration est le pont entre les objectifs et la réalité.",
      "Fais aujourd'hui ce que les autres ne font pas, pour pouvoir demain faire ce que les autres ne peuvent pas.",
      "Le vrai professionnel s'entraîne dur même quand personne ne le regarde.",
      "Ce ne sont pas les jours qui passent qui comptent, c'est ce que tu fais pour les rendre significatifs.",
    ],
    strong: [
      "Pendant que tu étudies les trajectoires et les mouvements pour anticiper le jeu, un autre court plus fort que toi pour te devancer.",
      "Le terrain ne ment jamais : tu peux inventer n'importe quelle excuse dans le vestiaire, mais tes quatre-vingt-dix minutes parlent exactement pour toi.",
      "Être sur le banc ou dans une équipe B n'est pas une condamnation : c'est la mesure exacte de ce que tu dois encore prouver à ceux qui n'ont pas cru en toi.",
      "Le ballon arrive où il doit arriver seulement si tu as la lucidité mentale pour le lire avant les autres. Si tu arrives en retard, ce n'est jamais la faute du coéquipier qui te l'a passé.",
      "La différence entre celui qui regarde le match et celui qui le décide se trouve dans cette seconde supplémentaire de sang-froid sous pression.",
      "Tu n'as pas besoin d'applaudissements. Tu as besoin d'une interception nette, d'un récupération désespérée et de la conscience d'avoir fermé la porte.",
      "Le talent sans une lecture lucide du jeu n'est qu'une course à vide.",
      "Si tu veux le maillot de titulaire dans l'équipe A, tu dois le mériter tellement que t'écarter devienne impossible pour l'entraîneur.",
      "Les crampes passent, la fatigue s'oublie, mais le regret de ne pas avoir tout donné dans ce duel reste avec toi pour toujours.",
      "Regarder les adversaires dans les yeux avant le coup de sifflet initial et savoir que tu as travaillé deux fois plus qu'eux en été : c'est la vraie confiance.",
      "La fatigue physique n'est qu'un mensonge que ton cerveau invente parce qu'il a peur de vraiment se donner.",
      "Tu n'apprends pas à frapper sous pression devant le public : tu l'apprends quand tu es seul à la fin de l'entraînement à répéter le même geste technique pour la centième fois.",
      "Ton rôle n'est pas ce qui est écrit sur le tableau tactique, c'est l'espace que tu arrives à conquérir avec ton intelligence.",
      "Un joueur médiocre cherche des coupables. Un athlète cherche des solutions dans sa propre performance.",
      "Si tu veux jouer à un niveau supérieur, tu dois commencer à penser à un niveau supérieur, avant même de toucher le ballon.",
      "Personne ne t'offrira un millimètre de terrain. Tu dois le prendre avec ta course, ta tête et ta technique.",
      "La fatigue est temporaire, l'étiquette de remplaçant te suit jusqu'à ce que tu prouves qui tu es.",
      "La sueur versée les jours où tu n'avais pas envie de descendre sur le terrain est la seule qui te sauvera quand le match devient difficile.",
      "Tu ne peux pas prétendre que l'équipe change de rythme si tu es le premier à ralentir quand le rythme augmente.",
      "Le terrain est le seul juge incorruptible. Et aujourd'hui, qu'a-t-il dit de toi ?",
    ],
    brutal: [
      "Tu gaspilles ton potentiel chaque fois que tu décides de te contenter parce qu'« il fait trop chaud aujourd'hui » ou « j'ai le temps ». Le temps ne te doit rien.",
      "Pendant que tu te reposes, quelque part quelqu'un a exactement le même rêve que toi, mais il transpire deux fois plus pour te l'arracher des mains.",
      "Tes excuses sont parfaites. Dommage qu'avec des excuses on ne gagne rien et on ne se fraye un chemin dans aucun championnat.",
      "Tu es exactement là où tu mérites être selon ce que tu as investi hier. Si ta situation actuelle ne te plaît pas, arrête de te plaindre et commence à travailler dur pour de vrai.",
      "La médiocrité se nourrit de « je commence demain ». As-tu vraiment commencé ou collectionnes-tu seulement des plans parfaits que tu n'exécutes pas ?",
      "Personne ne viendra te sauver, personne ne te prendra par la main pour t'emmener dans l'équipe A si tu ne prouves pas être un génie de la tête avant des pieds.",
      "Ton talent potentiel ne vaut pas un centime s'il reste enfermé dans ta tête. Ce que tu ne sors pas sur le terrain n'existe pas.",
      "Tu veux franchir un palier ? Arrête de planifier les apparences et commence à construire la substance, en te salissant les mains.",
      "Tu es ton premier saboteur quand tu reproches la malchance, l'entraîneur ou les autres pour un objectif que tu n'atteins pas.",
      "La vérité fait mal : si tu n'es pas le meilleur aujourd'hui, c'est parce que tu n'as pas fait ce qu'il fallait pour l'être.",
      "Tes rivaux n'ont aucune pitié pour toi. Pourquoi diable en aurais-tu pour toi-même quand tu t'entraînes ?",
      "Une routine parfaite, un plan parfait ne servent à rien si c'est toi qui abandonnes au meilleur moment.",
      "Arrête d'agir comme si tu avais tout le temps du monde. Ton âge est le moment où tu construis qui tu seras pour toujours ; le reste n'est que des distractions.",
      "Si tu continues à faire ce que tu as toujours fait, tu obtiendras exactement ce que tu as toujours eu : zéro.",
      "Ça fait mal de l'entendre, mais si tu n'es pas titulaire aujourd'hui, il y a une raison. Va la chercher dans le miroir et corrige-la.",
      "L'échec n'est pas de tomber ; l'échec c'est de décider de rester allongé à inventer une justification logique.",
      "Ce n'est pas de la chance qui te manque, c'est la faim féroce, celle qui te fait fermer les yeux et pousser quand ton corps supplie d'arrêter.",
      "Tout le monde veut gagner la coupe, mais très peu sont prêts à vomir de fatigue pour la mériter un mardi après-midi à portes closes.",
      "C'est toi qui décides si tu es un protagoniste ou un simple spectateur de ta propre vie. Choisis maintenant.",
      "Assez parlé. Éteins l'écran, ferme les onglets, lève-toi de cette chaise et va faire ce que tu dois faire.",
    ],
  },
  studente: {
    base: [
      "Le succès dans les études n'est pas un coup de chance, mais le résultat d'une planification constante et d'une méthode solide.",
      "Ne vise pas la perfection, vise la régularité. Chaque jour un petit pas en avant.",
      "L'esprit n'est pas un vase à remplir, mais un feu à allumer. – Plutarque",
      "La meilleure façon de prévoir ton avenir scolaire est de le créer aujourd'hui avec les livres ouverts.",
      "Le talent te donne l'étincelle, mais c'est la pratique quotidienne qui t'amène à la moyenne et puis à l'excellence.",
      "Celui qui étudie avec une méthode ne travaille pas deux fois plus la veille du contrôle.",
      "Chaque formule comprise, chaque théorème démontré et chaque page étudiée sont une brique pour ton demain.",
      "La concentration est le filtre qui sépare ceux qui étudient pour passer le contrôle de ceux qui étudient pour vraiment comprendre.",
      "Ne remets pas à demain ce que tu peux comprendre aujourd'hui : les dettes scolaires s'accumulent exactement comme les distractions.",
      "La discipline bat le talent chaque jour où le talent décide de ne pas ouvrir le livre.",
      "La note du contrôle n'est que le thermomètre du travail que tu as fourni les jours précédents.",
      "Une heure d'étude intense et ciblée vaut plus que quatre heures avec le livre ouvert et l'esprit ailleurs.",
      "La curiosité est le moteur de l'étudiant scientifique : ne mémorise pas, demande-toi toujours le pourquoi.",
      "Ne souhaite pas que le contrôle soit plus facile, souhaite avoir étudié plus en profondeur.",
      "La vraie étude, c'est celle que tu fais quand personne ne te contrôle et que la tentation de tout fermer est énorme.",
      "Se tromper sur un exercice à la maison sert à ne pas se tromper au contrôle le lendemain.",
      "La clarté d'un concept dans ton esprit se voit à la simplicité avec laquelle tu peux l'expliquer.",
      "Le temps investi dans les livres n'est jamais perdu, c'est le seul capital que personne ne pourra jamais t'enlever.",
      "Organiser sa journée d'étude signifie gagner la liberté de profiter du reste de l'après-midi.",
      "Fais aujourd'hui ce que les autres étudiants remettent à ce soir, ainsi demain tu seras un pas en avant.",
    ],
    strong: [
      "Pendant que tu te plains de la difficulté du programme de maths, un camarade est déjà en train de résoudre cette maudite intégrale qui ne rentre pas dans ta tête.",
      "Le bulletin électronique ne ment pas : tu ne peux pas blâmer le professeur si ta moyenne reflète exactement l'étude superficielle que tu as faite.",
      "La moyenne de sept ou huit ne se construit pas la veille du trimestre : elle se défend jour après jour avec l'interrogation programmée et l'exercice constant.",
      "Une insuffisance n'est pas la fin du monde, mais c'est une gifle qui doit te réveiller avant qu'elle ne devienne une dette en juin.",
      "La différence entre celui qui sort du lycée avec les félicitations et celui qui galère se trouve dans cette demi-heure supplémentaire à refaire les exercices jusqu'à ce que le mécanisme rentre dans tes doigts.",
      "Tu n'as pas besoin d'un coup de génie pour passer ; tu as besoin de la lucidité de lire le sujet et d'appliquer la méthode que tu as répétée à la maison.",
      "La fatigue mentale après trois heures de physique ou de latin est réelle, mais c'est justement là que se forme la vraie résistance de l'étudiant.",
      "Si tu veux viser les bonnes notes, tu dois arrêter d'étudier pour passer et commencer à étudier pour dominer la matière.",
      "Les professeurs voient tout de suite qui a compris le concept et qui a seulement mémorisé la petite règle sans savoir ce qu'elle signifie.",
      "Regarder la page blanche du contrôle et maudire le moment où tu as sauté les exercices de révision : c'est la leçon la plus dure que le lycée t'enseigne.",
      "La peur du contrôle disparaît au moment exact où tu sais que tu as refait ces exercices trois fois de suite à la maison.",
      "Tu ne peux pas prétendre comprendre la physique si tu abordes l'étude avec la même attention que pour faire défiler les réseaux sociaux.",
      "Ta note ne définit pas ta valeur en tant que personne, mais elle définit au millimètre l'efficacité de ta méthode d'étude et ton dévouement.",
      "Un étudiant médiocre cherche des excuses sur les livres trop difficiles ou les professeurs trop stricts. Un étudiant fort ouvre le manuel et apprend la démonstration.",
      "Si tu veux augmenter ta moyenne générale, tu dois commencer à traiter chaque matière comme si c'était la plus importante de ton bulletin.",
      "Personne ne t'offrira un point de plus par compassion. Au lycée scientifique les chiffres parlent clairement et les formules ne pardonnent pas les distractions.",
      "L'anxiété avant une interrogation n'est que la conséquence de ne pas te sentir prêt à 100 %. Remédie en te préparant tellement que la peur n'aura plus de place.",
      "La sueur sur les livres pendant les semaines les plus chargées est le seul prix à payer pour ne pas te retrouver le dos au mur à la fin de l'année.",
      "Tu ne peux pas prétendre que ton esprit soit brillant si tu le nourris de distractions constantes pendant que tu essaies d'étudier.",
      "Le bulletin est ouvert, la moyenne est calculée. Et aujourd'hui, qu'as-tu fait pour l'améliorer ?",
    ],
    brutal: [
      "Tu jettes ton potentiel aux toilettes chaque fois que tu dis « de toute façon je me débrouille avec un six », te contentant de la médiocrité.",
      "Pendant que tu procrastines avec le téléphone à la main, quelqu'un d'autre dans ta même classe étudie ce chapitre pour te voler la première place de la moyenne.",
      "Tes justifications sur « le prof m'en veut » sont pathétiques. Si tu as cinq, neuf fois sur dix c'est parce que tu n'as pas assez bien étudié.",
      "Tu es exactement là où ta paresse t'a mené. Si ton bulletin fait honte, arrête de blâmer le système scolaire et regarde-toi dans le miroir.",
      "Ta fausse technique du « de toute façon j'étudie à la dernière minute » ne marche que pour des choses triviales. Au lycée avancé elle te détruira sans pitié.",
      "Personne ne viendra sauver ta moyenne à la fin de l'année. Si tu ne t'y mets pas maintenant, tu sueras tes dettes tout seul en juillet.",
      "Ton intellect ne vaut pas un centime s'il est bloqué par la paresse mentale. Ce que tu ne comprends pas et n'approfondis pas reste un trou noir dans ta tête.",
      "Tu veux faire le malin, gérer tes affaires ? Commence par prouver que tu sais gérer une série de matières avancées sans te plaindre.",
      "Tu es ton premier saboteur quand tu éteins ton cerveau face à un problème de maths un peu plus long que d'habitude et que tu dis « je ne sais pas faire ça ».",
      "La dure vérité, c'est que si tu as des mauvaises notes aujourd'hui, ce n'est pas parce que l'école est injuste, mais parce que ton effort fait pitié comparé à ce que tu pourrais faire.",
      "Tes professeurs n'ont aucun intérêt à te faire échouer, mais ils n'ont pas non plus l'intention de t'offrir la promotion si tu ne lèves pas le petit doigt.",
      "Une idée de génie pour un logiciel ne vaut rien si tu échoues misérablement sur les bases scolaires parce que tu n'as pas envie de te concentrer.",
      "Arrête d'agir comme si l'école était une perte de temps. La façon dont tu abordes l'étude maintenant est exactement la façon dont tu aborderas n'importe quel travail d'adulte.",
      "Si tu continues à étudier avec le seul but de passer, tu obtiendras une vie médiocre. Réveille-toi.",
      "Ça fait mal de l'admettre, mais si tu ne comprends pas un sujet ce n'est pas parce que tu es nul, c'est parce que tu as lâché trop tôt à la première difficulté.",
      "L'échec à un contrôle n'est pas de la malchance ; l'échec c'est de décider de ne pas analyser les erreurs commises pour ne plus les répéter.",
      "Ce n'est pas l'intelligence qui te manque pour exceller au lycée scientifique : c'est la discipline de fer de t'asseoir pour étudier même quand la dernière chose que tu veux faire est d'ouvrir le livre.",
      "Tout le monde veut la moyenne de neuf et les applaudissements à la remise des diplômes, mais très peu sont prêts à éteindre leur téléphone et à suer sang sur les livres l'après-midi.",
      "C'est toi qui choisis d'être un étudiant médiocre qui survit aux interrogations ou une personne capable de dominer n'importe quelle matière devant elle.",
      "Assez d'excuses. Éteins les notifications, ouvre le livre à la bonne page et commence à étudier maintenant.",
    ],
  },
  professionista: {
    base: [
      "Le succès n'est pas définitif, l'échec n'est pas fatal : c'est le courage de continuer qui compte. – Winston Churchill",
      "Ne cherche pas des clients pour tes produits, trouve des produits pour tes clients. – Seth Godin",
      "La qualité, c'est faire les choses bien quand personne ne regarde. – Henry Ford",
      "La meilleure façon de prédire l'avenir est de l'inventer. – Alan Kay",
      "Le plus grand risque est de ne prendre aucun risque. Dans un monde qui change vite, la seule stratégie garantie d'échouer est de ne pas risquer. – Mark Zuckerberg",
      "Le prix du succès c'est le travail acharné, le dévouement et la détermination que, gagnons ou perdions, nous avons appliqué le meilleur de nous-mêmes à la tâche. – Vince Lombardi",
      "Ne te concentre pas sur avoir une grande entreprise ; concentre-toi sur la résolution d'un problème énorme de façon excellente.",
      "La discipline est le pont entre les objectifs et les résultats d'entreprise. – Jim Rohn",
      "Une entreprise prospère se fonde sur des décisions prises avec lucidité quand tout autour c'est le chaos.",
      "L'exécution bat l'idée brillante chaque jour de la semaine.",
      "Fais en sorte que tes clients soient tellement satisfaits qu'ils n'aient jamais à chercher ailleurs.",
      "Le profit est l'opinion du marché sur la valeur que tu crées.",
      "Celui qui n'innove pas et ne s'adapte pas finit par devenir irrélevant.",
      "Ne planifie pas pour le trimestre : planifie pour construire un écosystème qui dure dans le temps.",
      "Le vrai professionnel n'attend pas le moment parfait ; il prend le contrôle et le crée.",
      "La valeur d'une entreprise est directement proportionnelle aux problèmes réels qu'elle peut résoudre.",
      "La clarté de la vision détermine la vitesse des résultats.",
      "Le temps est la ressource la plus rare d'un entrepreneur : protège-le et investis-le seulement là où il y a un retour.",
      "Le succès commercial est la conséquence inévitable d'un produit excellent et d'une éthique de fer.",
      "Travaille sur ton projet avec la même intensité que tu exiges du marché qu'il te récompense.",
    ],
    strong: [
      "Pendant que tu analyses les détails pour la centième fois, quelqu'un d'autre sur le marché a lancé un produit imparfait mais opérationnel et te vole tes clients.",
      "Le marché n'a aucune pitié pour les idées non exécutées : elles valent zéro tant qu'elles ne génèrent pas de valeur réelle.",
      "La durabilité économique d'un projet ne se calcule pas sur des feuilles Excel optimistes, mais sur le nombre d'utilisateurs qui paient vraiment à la fin du mois.",
      "Un échec de marché n'est pas une malchance, c'est un retour brutal qui te dit que ton offre ne répond pas à un besoin réel.",
      "La différence entre ceux qui subissent le marché et ceux qui le dirigent réside dans la vitesse d'adaptation et le courage de couper les branches mortes.",
      "Tu n'as pas besoin d'un associé parfait ou d'un capital infini pour démarrer : tu as besoin d'une exécution impitoyable et de la capacité de vendre de la valeur.",
      "La fatigue mentale après une journée passée à résoudre des problèmes d'entreprise et techniques est le prix de l'indépendance.",
      "Si tu veux construire une entreprise solide, tu dois arrêter de chercher des excuses dans la bureaucratie ou la conjoncture économique et te concentrer sur ce que tu peux contrôler.",
      "Les clients n'achètent pas ton logiciel parce qu'il est beau : ils l'achètent parce qu'il résout un désagrément qui leur coûte du temps ou de l'argent.",
      "Regarder les métriques de conversion et voir zéro : c'est la réalité nue et crue qui t'oblige à corriger le tir.",
      "La pression financière et la recherche des premiers revenus ne sont pas un obstacle, c'est le filtre qui sépare ceux qui entreprennent par passion de ceux qui essaient par hobby.",
      "Tu ne peux pas prétendre que ton projet passe à l'échelle si tu es le premier goulot d'étranglement qui ne sait pas déléguer ni automatiser.",
      "Ta marque vaut exactement la confiance que le dernier utilisateur insatisfait place dans ton support.",
      "Un entrepreneur médiocre cherche des subventions et des excuses externes. Un vrai businessman cherche des canaux de distribution et optimise les coûts.",
      "Si tu veux facturer des chiffres importants, tu dois arrêter de penser petit et commencer à structurer chaque processus comme si l'entreprise avait dix mille utilisateurs.",
      "Personne ne t'offrira de la visibilité ou des conversions. Les parts de marché se conquièrent avec la bonne offre au bon moment.",
      "L'anxiété du lancement et de l'acquisition de clients disparaît seulement quand le produit est tellement utile qu'il se vend presque tout seul par le bouche-à-oreille.",
      "La sueur versée sur les bilans, le code ou les stratégies commerciales tard la nuit est le seul capital que personne ne pourra jamais t'enlever.",
      "Tu ne peux pas prétendre que ton business grandisse si tu traites ton activité avec la même superficialité qu'un passe-temps d'été.",
      "Le compte bancaire de l'entreprise est le seul juge incorruptible de ton efficacité. Et aujourd'hui, que dit-il de toi ?",
    ],
    brutal: [
      "Tu jettes ton temps et tes capacités aux toilettes chaque fois que tu inventes l'excuse que « le marché est saturé » ou « il manque des fonds ».",
      "Pendant que tu procrastines sur des détails esthétiques inutiles, dehors un concurrent affamé est en train de conclure des accords et de prendre tes clients potentiels.",
      "Tes justifications sur le fait que personne n'utilise ton app parce que « les gens ne comprennent pas la qualité » sont pathétiques. Si ça ne convertit pas, l'erreur est dans ton positionnement ou ton offre.",
      "Tu es exactement là où ton niveau d'exécution t'a mené. Si le projet stagne, arrête de blâmer les algorithmes et regarde-toi dans le miroir.",
      "Ta fausse stratégie d'« attendre que tout soit parfait avant de lancer » ne fait que te garantir d'arriver tard sur le marché.",
      "Personne ne viendra sauver ton entreprise ni t'apporter des clients à domicile. Si tu ne retrousses pas les manches pour faire de l'outreach et vendre, tu échoues.",
      "Ton code parfait ou tes idées géniales ne valent pas un centime si personne n'est prêt à payer pour les avoir. L'idée sans marché n'est pas un business, c'est un journal secret.",
      "Tu veux faire sérieux, tu veux facturer, tu veux ton indépendance financière ? Commence par prouver que tu sais générer le premier euro réel, sans te plaindre.",
      "Tu es ton premier saboteur quand tu lâches la prise commerciale dès que les choses deviennent difficiles et que les contacts ne répondent pas.",
      "La dure vérité, c'est que si ton business ne facture pas, ce n'est pas parce que le monde t'en veut, mais parce que ta proposition de valeur fait pitié ou personne ne sait la communiquer.",
      "Tes utilisateurs n'ont aucun intérêt à te rendre service : ils utiliseront ta plateforme seulement si elle résout un vrai problème mieux que n'importe qui d'autre.",
      "Une idée brillante sur papier ne vaut rien si tu échoues misérablement sur la gestion pratique, les échéances ou la relation client parce que tu n'as pas envie de te donner.",
      "Arrête d'agir comme si tu avais derrière toi un fonds d'investissement millionnaire qui couvre tes erreurs. L'argent se fait sur le terrain, en optimisant chaque ressource.",
      "Si tu continues à gérer ton projet avec la mentalité du « je le ferai quand j'en aurai envie », tu obtiendras un échec garanti. Réveille-toi.",
      "Ça fait mal de l'admettre, mais si un utilisateur essaie ton app et la ferme après deux secondes, ce n'est pas sa faute : c'est la tienne de ne pas avoir créé d'addiction ou d'utilité immédiate.",
      "L'échec d'un lancement n'est pas de la malchance ; l'échec c'est de décider de ne pas analyser les données des logs pour comprendre où tu t'es trompé.",
      "Ce n'est pas le talent qui te manque pour entreprendre : c'est la discipline de fer de te lever et de pousser la baraque même quand la réponse du marché est froide.",
      "Tout le monde veut la liberté financière et les projecteurs du succès, mais très peu sont prêts à assumer le risque, les non et le travail invisible dans les coulisses.",
      "C'est toi qui choisis d'être un chef de projet en papier qui collectionne les slides ou un entrepreneur qui transforme les problèmes en chiffre d'affaires.",
      "Assez d'excuses. Ferme les simulations théoriques, va parler au marché réel et commence à construire des résultats concrets maintenant.",
    ],
  },
  base: {
    base: [
      "Le succès n'est jamais accidentel ; c'est le résultat d'un travail acharné, de la persévérance et d'un sacrifice constant.",
      "L'excellence n'est pas un acte isolé, mais une habitude ancrée dans ce que tu fais chaque jour. – Aristote",
      "La motivation te fait démarrer, mais c'est une discipline de fer qui te mène jusqu'au bout.",
      "Ne t'arrête pas quand tu es fatigué, arrête-toi quand le travail est terminé. – David Goggins",
      "La meilleure façon de prévoir l'avenir est de le construire brique par brique avec tes actions d'aujourd'hui.",
      "Celui qui accepte de transpirer plus que les autres finit toujours par récolter les meilleurs fruits.",
      "Le prix de l'excellence, c'est la constance les jours où tu préférerais éviter la lutte.",
      "Gagne d'abord dans ton esprit, puis la réalité extérieure s'ajustera en conséquence.",
      "Le véritable professionnel accomplit la tâche même lorsque personne ne le regarde.",
      "Ce ne sont pas les jours qui passent qui comptent, mais uniquement l'intensité et la direction que tu donnes à chacun d'eux.",
    ],
    strong: [
      "Pendant que tu analyses des excuses pour remettre à plus tard, quelqu'un d'autre avec la même ambition que toi travaille d'arrache-pied pour prendre ta place.",
      "La réalité ne fait pas de rabais : ton niveau actuel reflète exactement l'investissement réel que tu as fait hier, pas tes intentions.",
      "La différence entre ceux qui subissent les événements et ceux qui les dirigent tient à la froideur avec laquelle ils lisent le contexte sous pression.",
      "Un résultat médiocre n'est pas une condamnation définitive, mais le miroir exact d'un engagement superficiel.",
      "La fatigue mentale et physique n'est qu'une frontière fictive que l'esprit érige pour se protéger de la vraie croissance.",
      "Si tu veux viser le sommet, tu dois cesser de te contenter de la suffisance et commencer à exiger l'excellence de toi.",
      "Personne ne t'offrira un millimètre d'espace : ta position, tu la gagnes à la sueur de ton front et tu la conquiers par ton esprit et tes actes.",
      "Le jugement du terrain, du marché ou des chiffres est incorruptible : il parle clairement et annule toute justification.",
      "L'anxiété et la peur disparaissent au moment précis où tu te prépares tellement que l'échec devient presque impossible.",
      "La sueur versée pendant les jours sombres est le seul capital qui te sauvera quand l'épreuve deviendra impitoyable.",
    ],
    brutal: [
      "Tu jettes ton potentiel chaque fois que tu choisis le chemin confortable des excuses plutôt que le chemin dur de l'exécution.",
      "Tes justifications sont parfaites, mais avec des justifications on n'a jamais rien construit de concret.",
      "Tu es exactement là où ta paresse t'a mené. Arrête de blâmer le système ou la malchance et regarde-toi dans le miroir.",
      "Ton talent potentiel ne vaut pas un seul centime tant qu'il reste enfermé dans ta tête sans se traduire en faits concrets.",
      "La médiocrité se nourrit de « je commence demain ». As-tu vraiment commencé ou collectionnes-tu seulement des plans théoriques parfaits ?",
      "Personne ne viendra te sauver, personne ne te prendra par la main. Si tu ne retrousses pas les manches le premier, tu resteras à regarder les autres gagner.",
      "La dure vérité, c'est que si tu n'obtiens pas ce que tu veux aujourd'hui, c'est parce que ton effort réel fait pitié comparé à tes grandes déclarations.",
      "Tout le monde veut la ligne d'arrivée et les applaudissements, mais très peu sont prêts à vomir de fatigue dans le silence des jours de semaine.",
      "Si tu continues à faire ce que tu as toujours fait, tu obtiendras exactement le rien que tu as en mains maintenant. Réveille-toi.",
      "Assez de bavardages, assez de simulations mentales : éteins les distractions, affronte le problème et va faire ce que tu dois.",
    ],
  },
};