export const it = {
  atleta: {
    base: [
      "Il successo non è mai accidentale. È lavoro duro, perseveranza, apprendimento, studio, sacrificio e, soprattutto, amore per ciò che fai. – Pelé",
      "Non misurarti per quello che hai raggiunto, ma per quello che avresti dovuto raggiungere con la tua abilità. – John Wooden",
      "L'eccellenza non è un atto isolato, ma un'abitudine. Tu sei ciò che fai ripetutamente. – Aristotele",
      "Il talento ti fa vincere la prima partita. Il lavoro di squadra e l'intelligenza ti fanno vincere il campionato. – Michael Jordan",
      "Se non ti sfidi, non ti cambi. – Fred DeVito",
      "Il modo per iniziare è smettere di parlare e iniziare a fare. – Walt Disney",
      "Non fermarti quando sei stanco. Fermati quando hai finito. – David Goggins",
      "I campioni continuano a giocare finché non fanno le cose nel modo giusto. – Billie Jean King",
      "Il fallimento è l'opportunità di ricominciare, questa volta in modo più intelligente. – Henry Ford",
      "La motivazione ti fa partire. L'abitudine ti fa continuare. – Jim Ryun",
      "Ogni giorno è una nuova opportunità per migliorare.",
      "Il sacrificio di oggi è il successo di domani.",
      "Chi è disposto a sudare più degli altri, alla fine raccoglie di più.",
      "Non desiderare che fosse più facile, desidera di essere migliore tu. – Jim Rohn",
      "Il prezzo dell'eccellenza è la disciplina costante.",
      "Vinci prima nella tua mente, poi sul campo.",
      "La concentrazione è il ponte tra gli obiettivi e la realtà.",
      "Fai oggi quello che gli altri non fanno, affinché domani tu possa fare ciò che gli altri non possono.",
      "Il vero professionista si allena duramente anche quando nessuno lo sta guardando.",
      "Non contano i giorni che passano, conta quello che fai per farli contare.",
    ],
    strong: [
      "Mentre tu studi le traiettorie e i movimenti per anticipare la giocata, un altro sta correndo più forte di te per bruciarti sul tempo.",
      "Il campo non mente mai: puoi inventarti qualsiasi scusa nello spogliatoio, ma i tuoi novanta minuti parlano esattamente per te.",
      "Essere in panchina o in una squadra B non è una condanna: è la misura esatta di quanto devi ancora dimostrare a chi non ha creduto in te.",
      "La palla arriva dove deve arrivare solo se hai la lucidità mentale di leggerla prima degli altri. Se arrivi in ritardo, la colpa non è mai del compagno che te l'ha passata.",
      "La differenza tra chi guarda la partita e chi la decide sta in quel secondo in più di freddezza sotto pressione.",
      "Non ti serve un applauso. Ti serve un'intercetta pulita, un recupero disperato e la consapevolezza di aver chiuso la porta.",
      "Il talento senza una lettura lucida del gioco è solo corsa a vuoto.",
      "Se vuoi la maglia da titolare nella squadra A, devi meritartela così tanto che tenerti fuori deve diventare impossibile per l'allenatore.",
      "I crampi passano, la fatica si dimentica, ma il rimpianto di non aver dato tutto in quel contrasto ti rimane addosso per sempre.",
      "Guardare gli avversari negli occhi prima del fischio d'inizio e sapere di aver lavorato il doppio di loro in estate: questa è la vera sicurezza.",
      "La fatica fisica è solo una bugia che il tuo cervello si inventa perché ha paura di faticare davvero.",
      "Non impari a calciare sotto pressione quando c'è il pubblico: impari a farlo quando sei da solo a fine allenamento a ripetere lo stesso gesto tecnico per la centesima volta.",
      "Il tuo ruolo non è quello che c'è scritto sulla lavagna tattica, è lo spazio che riesci a conquistare con la tua intelligenza.",
      "Un giocatore mediocre cerca colpevoli. Un atleta cerca soluzioni nel proprio rendimento.",
      "Se vuoi giocare a un livello superiore, devi iniziare a pensare a un livello superiore, prima ancora di toccare il pallone.",
      "Nessuno ti regalerà un millimetro di campo. Devi prendertelo con la corsa, con la testa e con la tecnica.",
      "La stanchezza è temporanea, l'etichetta di riserva te la porti dietro finché non dimostri chi sei.",
      "Il sudore versato nei giorni in cui non avevi voglia di scendere in campo è l'unico che ti salverà quando la partita si fa dura.",
      "Non puoi pretendere che la squadra cambi passo se sei il primo a rallentare quando il ritmo sale.",
      "Il campo è l'unico giudice incorruttibile. E oggi, cosa ha detto di te?",
    ],
    brutal: [
      "Stai sprecando il tuo potenziale ogni singola volta che decidi di accontentarti perché 'oggi fa troppo caldo' o 'tanto c'è tempo'. Il tempo non ti deve niente.",
      "Mentre tu stai riposando, là fuori c'è qualcuno che ha il tuo stesso identico sogno, ma sta sudando il doppio per strappartelo di mano.",
      "Le tue scuse sono perfette. Peccato che con le scuse non si vinca un bel niente e non si faccia strada in nessun campionato.",
      "Sei esattamente dove ti meriti di essere in base a quanto hai investito ieri. Se non ti piace la tua situazione attuale, smettila di lamentarti e comincia a faticare sul serio.",
      "La mediocrità si nutre di 'domani comincio'. Tu hai iniziato davvero o stai solo collezionando piani perfetti che non esegui?",
      "Nessuno verrà a salvarti, nessuno ti prenderà per mano per portarti nella squadra A se non dimostri di essere un fuoriclasse di testa prima che di piedi.",
      "Il tuo talento potenziale non vale un centesimo se resta chiuso nella tua testa. Quello che non tiri fuori sul campo non esiste.",
      "Vuoi fare il salto di qualità? Smettila di pianificare l'apparenza e inizia a costruire la sostanza, sporcandoti le mani.",
      "Sei tu il primo sabotatore di te stesso quando dai la colpa alla sfortuna, al mister o agli altri per un obiettivo che non stai raggiungendo.",
      "La verità fa schifo: se oggi non sei il migliore, è perché non hai fatto quello che serviva per esserlo.",
      "I tuoi rivali non hanno pietà di te. Perché diavolo dovresti averne tu di te stesso quando ti alleni?",
      "Un'applicazione perfetta, una routine perfetta non servono a nulla se poi sei tu che molli sul più bello.",
      "Smetti di comportarti come se avessi tutto il tempo del mondo. La tua età è il momento in cui costruisci chi sarai per sempre; il resto sono solo distrazioni.",
      "Se continui a fare quello che hai sempre fatto, otterrai esattamente quello che hai sempre avuto: zero.",
      "Fa male sentirselo dire, ma se oggi non giochi titolare, un motivo c'è. Vallo a cercare nello specchio e riparalo.",
      "Il fallimento non è cadere; il fallimento è decidere di rimanere sdraiati a inventarsi una giustificazione logica.",
      "Non ti manca la fortuna, ti manca la fame feroce, quella che ti fa chiudere gli occhi e spingere quando il corpo implora di smettere.",
      "Tutti vogliono vincere la coppa, ma pochissimi sono disposti a vomitare dalla fatica per meritarsela il martedì pomeriggio a porte chiuse.",
      "Sei tu che decidi se sei un protagonista o un semplice spettatore della tua stessa vita. Scegli adesso.",
      "Basta chiacchiere. Spegni lo schermo, chiudi le schede, alzati da quella sedia e vai a fare quello che devi fare.",
    ],
  },
  studente: {
    base: [
      "Il successo nello studio non è un colpo di fortuna, ma il risultato di una pianificazione costante e di un metodo solido.",
      "Non puntare a essere perfetto, punta a essere costante. Ogni giorno un piccolo passo avanti.",
      "La mente non è un vaso da riempire, ma un fuoco da accendere. – Plutarco",
      "Il modo migliore per prevedere il tuo futuro scolastico è creartelo oggi con i libri aperti.",
      "Il talento ti dà la scintilla, ma è l'esercizio quotidiano che ti porta a prendere la sufficienza piena e poi l'eccellenza.",
      "Chi studia con metodo non fatica il doppio la notte prima del compito in classe.",
      "Ogni formula capita, ogni teorema dimostrato e ogni pagina studiata sono un mattone per il tuo domani.",
      "La concentrazione è il filtro che separa chi studia per passare la verifica da chi studia per capire davvero.",
      "Non rimandare a domani quello che puoi capire oggi: i debiti formativi si accumulano esattamente come le distrazioni.",
      "La disciplina batte il talento ogni singolo giorno in cui il talento decide di non aprire il libro.",
      "Il voto della verifica è solo il termometro di quanto hai lavorato sodo nei giorni precedenti.",
      "Un'ora di studio intenso e mirato vale più di quattro ore passate con il libro aperto e la testa altrove.",
      "La curiosità è il motore dello studente scientifico: non imparare le cose a memoria, chiediti sempre il perché.",
      "Non desiderare che la verifica sia più facile, desidera di aver studiato con più profondità.",
      "Il vero studio è quello che fai quando nessuno ti controlla e la tentazione di chiudere tutto è altissima.",
      "Sbagliare un esercizio a casa serve a non sbagliare il compito in classe il giorno dopo.",
      "La chiarezza di un concetto nella tua mente si vede da quanto riesci a spiegarlo in modo semplice.",
      "Il tempo investito sui libri non è mai tempo perso, è l'unico capitale che nessuno potrà mai portarti via.",
      "Organizzare la propria giornata di studio significa guadagnare la libertà di godersi il resto del pomeriggio.",
      "Fai oggi quello che gli altri studenti rimandano a stasera, così domani sarai un passo avanti.",
    ],
    strong: [
      "Mentre tu ti lamenti della difficoltà del programma di matematica, un tuo compagno sta già risolvendo quel maledetto integrale che non ti entra in testa.",
      "Il registro elettronico non mente: non puoi dare la colpa al professore se la tua media riflette esattamente lo studio superficiale che hai fatto.",
      "La media del sette o dell'otto non si costruisce la sera prima del quadrimestre: si difende giorno dopo giorno con l'interrogazione programmata e l'esercizio costante.",
      "Un'insufficienza non è la fine del mondo, ma è uno schiaffo in faccia che deve svegliarti prima che diventi un debito a giugno.",
      "La differenza tra chi esce dal liceo con il massimo e chi arranca sta in quella mezz'ora in più passata a rifare gli esercizi finché il meccanismo non ti entra nelle dita.",
      "Non ti serve un colpo di genio fortunato per prendere la sufficienza; ti serve la lucidità di leggere la traccia e applicare il metodo che hai ripetuto a casa.",
      "La stanchezza mentale dopo tre ore di fisica o latino è vera, ma è proprio lì che si forma la vera resistenza dello studente.",
      "Se vuoi puntare ai voti alti, devi smettere di studiare per prendere la sufficienza e iniziare a studiare per dominare la materia.",
      "I professori vedono subito chi ha capito il concetto e chi ha solo imparato la regoletta a memoria senza sapere cosa significhi.",
      "Guardare la pagina bianca del compito in classe e maledire il momento in cui hai saltato gli esercizi di ripasso: questa è la lezione più dura che il liceo ti insegna.",
      "La paura del compito in classe sparisce nel momento esatto in cui sai di aver rifatto quegli esercizi tre volte di fila a casa.",
      "Non puoi pretendere di capire la fisica se affronti lo studio con la stessa attenzione con cui scorri i social sul telefono.",
      "Il tuo voto non definisce il tuo valore come persona, ma definisce al millimetro l'efficacia del tuo metodo di studio e la tua dedizione.",
      "Uno studente mediocre cerca scuse sui libri troppo difficili o sui professori severi. Uno studente forte apre il testo e impara la dimostrazione.",
      "Se vuoi alzare la tua media generale, devi iniziare a trattare ogni singola materia come se fosse la partita più importante della tua pagella.",
      "Nessuno ti regalerà un punto in più per compassione. Al liceo scientifico i numeri parlano chiaro e le formule non perdonano le distrazioni.",
      "L'ansia prima dell'interrogazione è solo la conseguenza di non sentirti pronto al 100%. Rimedia preparandoti così tanto che la paura non avrà spazio.",
      "Il sudore sui libri nelle settimane più pesanti è l'unico prezzo da pagare per non ritrovarsi con l'acqua alla gola alla fine dell'anno.",
      "Non puoi pretendere che la tua mente sia brillante se la nutri di distrazioni continue mentre cerchi di studiare.",
      "Il registro è aperto, la media è calcolata. E oggi, cosa hai fatto per migliorarla?",
    ],
    brutal: [
      "Stai buttando nel wc il tuo potenziale ogni volta che dici 'tanto il sei lo strappo comunque', accontentandoti della mediocrità.",
      "Mentre tu stai procrastinando con il telefono in mano, c'è qualcun altro nella tua stessa classe che sta studiando quel capitolo per rubarti il podio della media più alta.",
      "Le tue giustificazioni sul 'prof ce l'ha con me' sono patetiche. Se prendi cinque, nove volte su dieci è perché non hai studiato abbastanza bene.",
      "Sei esattamente dove la tua pigrizia ti ha portato. Se la tua pagella fa schifo, smettila di dare la colpa al sistema scolastico e guardati allo specchio.",
      "La tua finta tecnica del 'tanto io studio all'ultimo minuto' funziona solo finché fai cose banali. Alle superiori avanzate ti distruggerà senza pietà.",
      "Nessuno verrà a salvarti la media a fine anno. Se non ti metti sotto adesso, i debiti te li sudi tutti da solo a luglio.",
      "Il tuo intelletto non vale un centesimo se è bloccato dalla pigrizia mentale. Quello che non capisci e non approfondisci rimane un buco nero nella tua testa.",
      "Vuoi fare il grande, vuoi gestirti le tue cose? Comincia col dimostrare di saper gestire una sfilza di materie superiori senza piangerti addosso.",
      "Sei tu il primo a sabotarti quando spegni il cervello davanti a un problema di matematica un po' più lungo del solito e dici 'questo non lo so fare'.",
      "La dura verità è che se oggi prendi voti bassi, non è perché la scuola è ingiusta, ma perché il tuo impegno fa pena rispetto a quello che potresti fare.",
      "I tuoi professori non hanno alcun interesse a farti fallire, ma non hanno neanche intenzione di regalarti la promozione se non muovi un dito.",
      "Un'idea geniale per un software non vale nulla se poi caschi miseramente sulle basi scolastiche perché non hai voglia di concentrarti.",
      "Smetti di comportarti come se la scuola fosse una perdita di tempo. Il modo in cui affronti lo studio adesso è esattamente il modo in cui affronterai qualsiasi lavoro da adulto.",
      "Se continui a studiare con la sufficienza come unico traguardo, otterrai una vita mediocre. Svegliati.",
      "Fa male ammetterlo, ma se non capisci un argomento non è perché sei negato, è perché hai mollato la presa troppo presto alla prima difficoltà.",
      "Il fallimento in una verifica non è una sfortuna; il fallimento è decidere di non analizzare gli errori commessi per non ripeterli mai più.",
      "Non ti manca l'intelligenza per eccellere al liceo scientifico: ti manca la disciplina ferrea di metterti lì a studiare anche quando l'ultima cosa che vorresti fare è aprire il libro.",
      "Tutti vogliono la media del nove e gli applausi alla consegna dei diplomi, ma pochissimi sono disposti a spegnere il telefono e sputare sangue sui libri il pomeriggio.",
      "Sei tu che scegli se essere uno studente mediocre che sopravvive alle interrogazioni o una persona capace di dominare qualsiasi materia si trovi davanti.",
      "Basta scuse. Spegni le notifiche, apri il libro sulla pagina giusta e comincia a studiare adesso.",
    ],
  },
  professionista: {
    base: [
      "Il successo non è definitivo, il fallimento non è fatale: ciò che conta è il coraggio di continuare. – Winston Churchill",
      "Non trovare clienti per i tuoi prodotti, trova prodotti per i tuoi clienti. – Seth Godin",
      "La qualità significa fare le cose bene quando nessuno ti sta guardando. – Henry Ford",
      "Il modo migliore per prevedere il futuro è inventarlo. – Alan Kay",
      "Il rischio più grande è non rischiare nulla. In un mondo che cambia rapidamente, l'unica strategia garantita per fallire è non rischiare. – Mark Zuckerberg",
      "Il prezzo del successo è il duro lavoro, la dedizione e la determinazione che, vinciamo o perdiamo, abbiamo applicato il meglio di noi stessi al compito. – Vince Lombardi",
      "Non concentrarti su avere una grande azienda; concentrati su risolvere un problema enorme in modo eccellente.",
      "La disciplina è il ponte tra gli obiettivi e i risultati aziendali. – Jim Rohn",
      "Il business di successo si fonda su decisioni prese con lucidità quando tutto intorno c'è il caos.",
      "L'esecuzione batte l'idea brillante ogni singolo giorno della settimana.",
      "Fai in modo che i tuoi clienti siano così soddisfatti che non debbano mai guardare altrove.",
      "Il profitto è l'opinione del mercato sul valore che stai creando.",
      "Chi non innova e non si adatta finisce per diventare irrilevante.",
      "Non pianificare per il trimestre: pianifica per costruire un ecosistema che duri nel tempo.",
      "Il vero professionista non aspetta il momento perfetto; prende il controllo della situazione e lo crea.",
      "Il valore di un'azienda è direttamente proporzionale ai problemi reali che riesce a risolvere.",
      "La chiarezza della visione determina la velocità dei risultati.",
      "Il tempo è la risorsa più scarsa di un imprenditore: proteggilo e investilo solo dove c'è ritorno.",
      "Il successo commerciale è la conseguenza inevitabile di un prodotto eccellente e di un'etica ferrea.",
      "Lavora sul tuo progetto con la stessa intensità con cui pretendi che il mercato ti ripaghi.",
    ],
    strong: [
      "Mentre tu analizzi i dettagli per la centesima volta, qualcun altro sul mercato ha lanciato un prodotto imperfetto ma operativo e ti sta rubando i clienti.",
      "Il mercato non ha alcuna pietà per le idee non eseguite: valgono zero finché non generano valore reale.",
      "La sostenibilità economica di un progetto non si calcola sui fogli di Excel ottimistici, ma su quanti utenti pagano davvero a fine mese.",
      "Un fallimento di mercato non è una sfortuna, è un feedback brutale che ti dice che la tua offerta non risponde a un bisogno reale.",
      "La differenza tra chi subisce il mercato e chi lo guida sta nella velocità di adattamento e nel coraggio di tagliare i rami secchi.",
      "Non ti serve un socio perfetto o un capitale infinito per partire: ti serve un'esecuzione spietata e la capacità di vendere valore.",
      "La stanchezza mentale dopo una giornata passata a risolvere grane aziendali e tecniche è il prezzo dell'indipendenza.",
      "Se vuoi costruire un business solido, devi smettere di cercare le scuse della burocrazia o della congiuntura economica e focalizzarti su ciò che puoi controllare.",
      "I clienti non comprano il tuo software perché è bello: lo comprano perché gli risolve un fastidio che gli costa tempo o denaro.",
      "Guardare le metriche di conversione e vedere zero: questa è la realtà nuda e cruda che ti costringe a raddrizzare il tiro.",
      "La pressione finanziaria e la ricerca dei primi ricavi non sono un ostacolo, sono il filtro che separa chi fa impresa per passione da chi ci prova per hobby.",
      "Non puoi pretendere che il tuo progetto scali se tu sei il primo collo di bottiglia che non sa delegare o automatizzare.",
      "Il tuo brand vale esattamente quanto la fiducia che l'ultimo utente insoddisfatto ripone nella tua assistenza.",
      "Un imprenditore mediocre cerca sussidi e scuse esterne. Un businessman vero cerca canali di distribuzione e ottimizza i costi.",
      "Se vuoi fatturare cifre importanti, devi smettere di pensare in piccolo e iniziare a strutturare ogni processo come se l'azienda avesse diecimila utenti.",
      "Nessuno ti regalerà visibilità o conversioni. Le quote di mercato si conquistano con l'offerta giusta al momento giusto.",
      "L'ansia del lancio e dell'acquisizione clienti sparisce solo quando il prodotto è talmente utile che si vende quasi da solo tramite passaparola.",
      "Il sudore versato sui bilanci, sul codice o sulle strategie commerciali a notte fonda è l'unico capitale che nessuno potrà mai portarti via.",
      "Non puoi pretendere che il tuo business cresca se tratti la tua attività con la stessa superficialità di un passatempo estivo.",
      "Il conto in banca aziendale è l'unico giudice incorruttibile della tua efficacia. E oggi, cosa dice di te?",
    ],
    brutal: [
      "Stai buttando nel water il tuo tempo e le tue capacità ogni volta che ti inventi la scusa che 'il mercato è saturo' o che 'mancano i fondi'.",
      "Mentre tu stai procrastinando dietro a dettagli estetici inutili, là fuori c'è un concorrente affamato che sta chiudendo accordi e prendendosi i tuoi potenziali clienti.",
      "Le tue giustificazioni sul fatto che nessuno usa la tua app perché 'la gente non capisce la qualità' sono patetiche. Se non converte, l'errore è nel tuo posizionamento o nella tua offerta.",
      "Sei esattamente dove il tuo livello di esecuzione ti ha portato. Se il progetto ristagna, smettila di dare la colpa agli algoritmi e guardati allo specchio.",
      "La tua finta strategia del 'aspetto che sia tutto perfetto prima di uscire' ti sta solo garantendo di arrivare tardi sul mercato.",
      "Nessuno verrà a salvarti l'azienda o a portarti i clienti a casa. Se non ti rimbocchi le mani per fare outreach e vendere, fallisci.",
      "Il tuo codice perfetto o le tue idee geniali non valgono un centesimo se non c'è nessuno disposto a pagare per averli. L'idea senza mercato non è un business, è un diario segreto.",
      "Vuoi fare sul serio, vuoi fatturare, vuoi la tua indipendenza economica? Comincia col dimostrare di saper generare il primo euro reale, senza piangerti addosso.",
      "Sei tu il primo a sabotarti quando molli la presa commerciale appena le cose si fanno difficili e i contatti non rispondono.",
      "La dura verità è che se il tuo business non fattura, non è perché il mondo ce l'ha con te, ma perché la tua proposta di valore fa pena o non la sa comunicare nessuno.",
      "I tuoi utenti non hanno alcun interesse a farti un favore: useranno la tua piattaforma solo se risolve un loro problema reale meglio di chiunque altro.",
      "Un'idea brillante sulla carta non vale nulla se caschi miseramente sulla gestione pratica, sulle scadenze o sul rapporto con il cliente perché non hai voglia di sbatterti.",
      "Smetti di comportarti come se avessi alle spalle un fondo d'investimento milionario che copre i tuoi errori. I soldi si fanno sul campo, ottimizzando ogni singola risorsa.",
      "Se continui a gestire il tuo progetto con la mentalità del 'tanto lo faccio quando ho voglia', otterrai un fallimento garantito. Svegliati.",
      "Fa male ammetterlo, ma se un utente prova la tua app e la chiude dopo due secondi, non è colpa sua: è colpa tua che non hai creato dipendenza o utilità immediata.",
      "Il fallimento di un lancio non è una sfortuna; il fallimento è decidere di non analizzare i dati dei log per capire dove hai sbagliato.",
      "Non ti manca il talento per fare impresa: ti manca la disciplina ferrea di alzarti e spingere la baracca anche quando la risposta del mercato è fredda.",
      "Tutti vogliono la libertà finanziaria e i riflettori del successo, ma pochissimi sono disposti a farsi carico del rischio, dei no e del lavoro invisibile dietro le quinte.",
      "Sei tu che scegli se essere un project manager di carta che colleziona slide o un imprenditore che trasforma i problemi in fatturato.",
      "Basta scuse. Chiudi le simulazioni teoriche, vai a parlare con il mercato reale e comincia a costruire risultati concreti adesso.",
    ],
  },
  base: {
    base: [
      "Il successo non è mai accidentale; è il risultato di lavoro duro, perseveranza e sacrificio costante.",
      "L'eccellenza non è un atto isolato, ma un'abitudine radicata in ciò che fai ogni giorno. – Aristotele",
      "La motivazione ti fa partire, ma è la disciplina ferrea che ti fa arrivare fino in fondo.",
      "Non fermarti quando sei stanco, fermati quando hai completato l'opera. – David Goggins",
      "Il modo migliore per prevedere il futuro è costruirlo mattone dopo mattone con le tue azioni odierne.",
      "Chi è disposto a sudare più degli altri, alla fine raccoglie sempre i frutti migliori.",
      "Il prezzo dell'eccellenza è la costanza nei giorni in cui faresti volentieri a meno di lottare.",
      "Vinci prima nella tua mente, poi la realtà esterna si adeguerà di conseguenza.",
      "Il vero professionista porta a termine il compito anche quando nessuno lo sta guardando.",
      "Non contano i giorni che passano, conta unicamente l'intensità e la direzione che dai a ciascuno di essi.",
    ],
    strong: [
      "Mentre tu analizzi le scuse per rimandare, qualcun altro con la tua stessa ambizione sta sgobbando per prendersi il tuo posto.",
      "La realtà non fa sconti: il tuo livello attuale riflette esattamente l'investimento reale che hai fatto ieri, non le tue intenzioni.",
      "La differenza tra chi subisce gli eventi e chi li guida sta nella freddezza con cui legge il contesto sotto pressione.",
      "Un risultato mediocre non è una condanna definitiva, ma è lo specchio esatto di un impegno superficiale.",
      "La stanchezza mentale e fisica è solo un confine fittizio che la mente erige per proteggersi dalla vera crescita.",
      "Se vuoi puntare al vertice, devi smettere di accontentarti della sufficienza e iniziare a pretendere l'eccellenza da te stesso.",
      "Nessuno ti regalerà un millimetro di spazio: la tua posizione te la sudi e te la conquisti con la testa e con i fatti.",
      "Il giudizio del campo, del mercato o dei numeri è incorruttibile: parla chiaro e azzera ogni giustificazione.",
      "L'ansia e la paura spariscono nel momento esatto in cui ti prepari così tanto da rendere il fallimento quasi impossibile.",
      "Il sudore versato nei giorni bui è l'unico capitale che ti salverà quando la prova si farà spietata.",
    ],
    brutal: [
      "Stai buttando via il tuo potenziale ogni singola volta che scegli la comoda via della scusa anziché la dura via dell'esecuzione.",
      "Le tue giustificazioni sono perfette, ma con le giustificazioni non si è mai costruito un cazzo di niente.",
      "Sei esattamente dove la tua pigrizia ti ha portato. Smettila di dare la colpa al sistema o alla sfortuna e guardati allo specchio.",
      "Il tuo talento potenziale non vale un singolo centesimo finché resta chiuso nella tua testa senza tradursi in fatti concreti.",
      "La mediocrità si nutre di 'domani comincio'. Tu hai iniziato davvero o stai solo collezionando piani teorici perfetti?",
      "Nessuno verrà a salvarti, nessuno ti prenderà per mano. Se non ti rimbocchi le maniche per primo, rimarrai a guardare gli altri vincere.",
      "La dura verità è che se oggi non ottieni ciò che vuoi, è perché il tuo impegno reale fa pena rispetto ai tuoi grandi proclami.",
      "Tutti vogliono il traguardo e gli applausi, ma pochissimi sono disposti a vomitare dalla fatica nel silenzio dei giorni feriali.",
      "Se continui a fare quello che hai sempre fatto, otterrai esattamente il nulla che hai in mano adesso. Svegliati.",
      "Basta chiacchiere, basta simulazioni mentali: spegni le distrazioni, affronta il problema e vai a fare ciò che devi.",
    ],
  },
};